# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

[project]
name = "cinder-volume-lvm-san"
version = "2026.1"
requires-python = "~=3.12.0"

dependencies = [
    "cryptography",
    "jinja2",
    "pydantic",
    "lightkube",
    "lightkube-models",
    "requests",
    "ops",
    "ops-sunbeam@git+https://opendev.org/openstack/sunbeam-charms#subdirectory=ops-sunbeam",
    "interface_tls_certificates@git+https://opendev.org/openstack/charm-ops-interface-tls-certificates",
    "interface_ceph_client@git+https://opendev.org/openstack/charm-ops-interface-ceph-client",
    "charmhelpers@git+https://github.com/juju/charm-helpers.git",
    "netifaces",
    "tenacity",
    "opentelemetry-api~=1.21.0",
]
